server:
  port: 8090
  servlet:
    context-path: /illusion
    
    
    
    
########################################################  
###THYMELEAF (ThymeleafAutoConfiguration)  
########################################################  
#spring.thymeleaf.prefix=classpath:/templates/  
#spring.thymeleaf.suffix=.html  
#spring.thymeleaf.mode=HTML5  
#spring.thymeleaf.encoding=UTF-8  
# ;charset=<encoding> is added  
#spring.thymeleaf.content-type=text/html  
# set to false for hot refresh  
#spring.thymeleaf.cache=false  

spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
    
  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    content-type: text/html
    cache: false  
  
  
  




    